include_recipe '../../cookbooks/linux/default.rb'
include_recipe '../../cookbooks/php/default.rb'
include_recipe '../../cookbooks/apache/default.rb'
include_recipe '../../cookbooks/mysql/default.rb'
include_recipe '../../cookbooks/rainloop/default.rb'
